# Generated by Django 6.0.3 on 2026-06-08 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
