# Generated by Django 6.0.3 on 2026-06-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reserva_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.CharField(choices=[('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00')], max_length=5),
        ),
    ]
